AppBundle\Entity\Navigation:
    type: entity
    table: navigation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        url:
            type: string
            length: 255
        is_public:
            type: boolean
            options:
                default: 1
        created_at:
            type: datetime
    oneToMany:
        children:
            targetEntity: Navigation
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: Navigation
            inversedBy: children
            joinColumn:
                onDelete: CASCADE
            