AppBundle\Entity\Navigation:
    type: entity
    table: navigation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        url:
            type: string
            length: 255
        description:
            type: text